services:
  authelia:
    container_name: ${CONTAINER_NAME}
    image: authelia/authelia:4.38.17
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9091"
    volumes:
      - ./data:/config
    labels:
      createdBy: "Apps"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${PANEL_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_SESSION_SECRET=${PANEL_SESSION_SECRET}
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=${PANEL_RESET_PWD_SECRET}

networks:
  1panel-network:
    external: true
