services:
  authelia:
    container_name: ${CONTAINER_NAME}
    image: authelia/authelia:4.38.17
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9091"
    volumes:
      - ./data:/config
    labels:
      createdBy: "Apps"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/secrets/STORAGE_ENCRYPTION
      - AUTHELIA_SESSION_SECRET_FILE=/config/secrets/SESSION_SECRET
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/config/secrets/JWT_SECRET
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET=/config/secrets/HMAC_SECRET

networks:
  1panel-network:
    external: true
