services:
  lagrange:
    image: ghcr.io/lagrangedev/lagrange.onebot:edge
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - TZ=${TIME_ZONE}
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8081
    volumes:
      - ./data:/app/data
    labels:
      createdBy: "Apps"
networks:
    1panel-network:
        external: true