services:
  syncthing-discosrv:
    container_name: ${CONTAINER_NAME}
    image: syncthing/discosrv:1.28.0
    restart: always
    command: --debug --http --listen=":8443"
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8443"
    volumes:
      - ./data:/var/stdiscosrv
    labels:
      createdBy: "Apps"
    environment:
      - PUID=1000
      - PGID=1000

networks:
  1panel-network:
    external: true